reactive_circumnav:
  ros__parameters:
    mode_c_control_type: "relay"  # "relay", "barrier", "sta", "curv"
    odom_topic: "/odom"
    scan_topic: "/scan"
    telemetry_log_path: "/home/user/workspace/src/reactive_circumnav/results/chattering_relay_ss.csv"
    linear_velocity: 1.0 #1.0
    angular_velocity: 2.0  #0.6666666
    rho_0: 2.0
    R_epsilon: 0.0
    R_vis: 12.0
    resolution: 360
    lidar_angle_offset: 3.14159
    window_size: 10
    nu: 100.0
    curvature_points_size: 10
    k1: 1.80
    k2: 0.4