reactive_circumnav:
  ros__parameters:
    telemetry_log_path: "/home/user/ros2_ws/src/reactive_circumnav/results/controller_telemetry.csv"
    linear_velocity: 0.5
    angular_velocity: 1.0
    rho_0: 2.0
    R_epsilon: 0.0
    R_vis: 12.0
    resolution: 360
    lidar_angle_offset: 0.0 #3.14159
    window_size: 20
    nu: 100.0
    history_size: 10
    